name: fakestore-backend-drf
services:
  app:
    image: eduardosilvasc/fakestore-backend-drf:latest
    environment:
      - MODE=DEVELOPMENT #  possible values are: DEVELOPMENT, PRODUCTION, MIGRATE
      - SECRET_KEY=z^5fokn4d-vpe87mq4u252fzwb7%xv#fh$p3=#_pwxnrm1cly6
      - DEBUG=True #  possible values are: True, False
      - PASSAGE_APP_ID=5DAaOaVZqqNtEpUNvpeRIiTG
      - PASSAGE_API_KEY=UH55sr9dY9.t9HcFaqUCZNqJnhDGOyyGElHrR6CUTVeUhFV5Virw9vmLUJZ5aiDrmiOYfdjQ2zY
    ports:
      - 8000:8000